services:
  mytaxidb:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=my_taxi
    networks:
      - pgnetwork
    volumes:
      - ./my_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  mypgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - ./my_pg_admin_data/pgadmin:/var/lib/pgadmin
    networks:
      - pgnetwork
    ports:
      - "8080:80"

networks:
  pgnetwork:
    name: pgnetwork
